[tool.poetry]
name = "algorithm"
version = "0.1.0"
description = ""
authors = ["realaashil <singhalaashil@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
